version: "3.7"
services:
  app:
    build:
      args:
        user: dwihardik
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: voyager
    container_name: voyager-laravel
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - voyager

  db:
    image: mysql:8.0
    container_name: voyager-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: voyager
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: voyager
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - voyager

  nginx:
    image: nginx:alpine
    container_name: voyager-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginxvoyager:/etc/nginx/conf.d/
    networks:
      - voyager

networks:
  voyager:
    driver: bridge